#!/usr/bin/env python3

description = """
    👽 EMOJIPHER 👽
    
    Your favorite encryption tool!
    
    Are you bored of cryptographically safe means of encryption like AES256?
    You hate asymmetric encryption?
    You are a modern human that loves big hard drives and emojis?
    You want to waste as much bandwith as you can?
    You want to choke NSA and TENCENT servers with emoji?

    If you answered any of those questions with YES, this script is for you.
    
    Encrypt your data by turning each byte of source file into emoji! Yes, thats right.
    Each byte becomes 4 bytes! And you get multiple emoji possibilities per byte!
    Frequency analysis? More like waste of electricity.
    
    Okay, I want this, but how do I start?
    
    1. Generate your personal key by issuing. It will append .emojipher to the end of your given name.
        $ ./emojipher.py -g my_key
        
    2. Encrypt some data!
        $ ./emojipher.py -e my_secrets.txt -k my_key.emojipher
        
    3. ... Do whatever you want, store it, send it, share it 🤡
    
    4. Decrypt your precious data.
        $ ./emojipher.py -d my_secrets.txt.encrypted -k my_key.emojipher
        
    5. Enjoy your decrypted data, but make sure you are alone.
    
    Made with 🤡 by the 🤤 in www.exception.lt
    """

changelog = """
👽 EMOJIPHER CHANGELOG 👽

10.10.2020
+ made everything async, because why not. i have not checked if it made it faster/slower, but added because it is hype to do async.
+ fixed decryption making file disappear.
- removed emojipedia depedency by hardcoding emojis into the file. 5kb to 25kb file, but no pip installs needed. uses standardlib. if argparse is in standardlib.
+ decrypted message does not replace og message, it will be named <input_file>.decrypted, like you pass <message_file>.encrypted to the decryptor.

"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter

# from emojipedia import (
#    Emojipedia,
# )  # replace with a massive list of hardcoded emojis lol.
import asyncio
import secrets
import os.path
import ast


async def get_all_emojis() -> set:
    """You like hardcoded emoji set? Here you go ;)"""
    # return set([x.character for x in Emojipedia.all() if len(str(x.character)) == 1])

    return {
        "💆",
        "🕐",
        "🥁",
        "📣",
        "🐮",
        "🏈",
        "\U0001faa2",
        "🍁",
        "🦲",
        "📥",
        "\U0001f9a4",
        "💜",
        "🌻",
        "📌",
        "🍋",
        "🦯",
        "🇿",
        "🏭",
        "📐",
        "🌰",
        "🌇",
        "\U000e0034",
        "🎾",
        "🏩",
        "\U000e0072",
        "🤦",
        "🐨",
        "🧉",
        "🇪",
        "🎪",
        "🛀",
        "🐌",
        "🔗",
        "🥢",
        "💀",
        "\U000e005e",
        "🐜",
        "🤡",
        "\U000e006a",
        "🎠",
        "🐳",
        "\U0001fa9a",
        "\U000e005c",
        "\U000e0049",
        "🚧",
        "🥉",
        "👾",
        "🌈",
        "\U000e004f",
        "👡",
        "👑",
        "🔅",
        "⬛",
        "🥈",
        "🚹",
        "🚄",
        "🥏",
        "\U0001fab1",
        "🚒",
        "🕠",
        "💯",
        "🤲",
        "🧅",
        "💲",
        "🤗",
        "😺",
        "👚",
        "🔼",
        "🕜",
        "🆘",
        "☔",
        "🔦",
        "🍰",
        "🥋",
        "💹",
        "\U000e002a",
        "🟦",
        "🍱",
        "🏤",
        "🦖",
        "🌊",
        "🥄",
        "😁",
        "😖",
        "🍇",
        "🧤",
        "📃",
        "🌉",
        "📉",
        "💠",
        "🧑",
        "🥤",
        "🔶",
        "🐱",
        "📛",
        "🐘",
        "🌋",
        "😳",
        "🎈",
        "😄",
        "🍕",
        "🥾",
        "⚽",
        "😧",
        "😞",
        "\U0001fab0",
        "🍨",
        "\U0001f977",
        "🥍",
        "🛂",
        "☕",
        "📁",
        "💣",
        "🔠",
        "🔕",
        "🔔",
        "📔",
        "\U000e0023",
        "🎏",
        "🤺",
        "🈴",
        "👵",
        "🧄",
        "🦟",
        "🎼",
        "🚍",
        "👊",
        "🔭",
        "🕧",
        "🤖",
        "🙊",
        "♐",
        "💻",
        "\U000e003b",
        "🛹",
        "🌁",
        "\U000e0042",
        "🍊",
        "\U000e0066",
        "🧗",
        "\U000e0053",
        "🍵",
        "🎊",
        "🖖",
        "🧎",
        "🚋",
        "🗽",
        "👢",
        "🌌",
        "🎹",
        "😉",
        "🤚",
        "👷",
        "\U000e0031",
        "🤙",
        "🦐",
        "🇩",
        "🔓",
        "🚝",
        "🚜",
        "😴",
        "🤣",
        "\U000e002e",
        "🍟",
        "\U0001f9ac",
        "📵",
        "🌍",
        "\U000e004a",
        "\U000e0030",
        "👬",
        "🎎",
        "📠",
        "📘",
        "🩸",
        "\U000e002c",
        "🏂",
        "⌚",
        "\U000e0033",
        "\U000e0071",
        "💶",
        "🐙",
        "🧫",
        "🏃",
        "🐝",
        "⚓",
        "🕎",
        "❌",
        "➖",
        "📖",
        "👫",
        "🌠",
        "😆",
        "🤟",
        "🌷",
        "🟩",
        "🦧",
        "💈",
        "🏦",
        "🍴",
        "🀄",
        "💴",
        "♓",
        "🦺",
        "\u200d",
        "🏾",
        "🦴",
        "🎓",
        "🎉",
        "🍡",
        "\U000e0036",
        "🥟",
        "👔",
        "👌",
        "🎷",
        "🧾",
        "🛑",
        "😪",
        "😜",
        "\U0001fa74",
        "🔤",
        "🎍",
        "🕔",
        "🔝",
        "📚",
        "🕞",
        "📱",
        "\U000e0076",
        "\U000e0070",
        "🐾",
        "🛸",
        "🧁",
        "🦨",
        "🏨",
        "🐸",
        "📑",
        "🏡",
        "\U0001faa1",
        "◾",
        "\U0001fa98",
        "🐔",
        "🚈",
        "🕟",
        "🚑",
        "🆓",
        "\U000e0077",
        "🈵",
        "\U000e005f",
        "\U000e003f",
        "🧸",
        "🇴",
        "🎻",
        "🌯",
        "🍳",
        "\U000e004c",
        "💃",
        "🌭",
        "🧔",
        "\U000e0057",
        "📤",
        "🦈",
        "🐥",
        "🍝",
        "🚌",
        "🤿",
        "🧝",
        "💤",
        "😚",
        "👈",
        "🧓",
        "🇭",
        "🍛",
        "📜",
        "🤎",
        "🚿",
        "🚲",
        "💢",
        "🪀",
        "👃",
        "🕒",
        "🦷",
        "🥜",
        "\U000e0064",
        "🚅",
        "📰",
        "🎑",
        "📮",
        "💸",
        "🍞",
        "🎒",
        "\U000e0021",
        "🧮",
        "🎁",
        "🦑",
        "\U0001fad6",
        "📆",
        "🧍",
        "💿",
        "👍",
        "😯",
        "⛺",
        "🥌",
        "🍒",
        "👗",
        "🤍",
        "🐣",
        "🉑",
        "🈯",
        "🍻",
        "\U000e0027",
        "\U000e0056",
        "🦝",
        "🦍",
        "🐧",
        "📅",
        "🆕",
        "👯",
        "😥",
        "🧊",
        "🚉",
        "💱",
        "🦢",
        "😇",
        "🕝",
        "📹",
        "🚃",
        "🙍",
        "🏻",
        "🔒",
        "🦩",
        "📎",
        "😛",
        "🙉",
        "🌼",
        "👂",
        "🥅",
        "🤛",
        "⃣",
        "👒",
        "🎳",
        "\U000e0059",
        "📻",
        "🤕",
        "🐰",
        "🕙",
        "🍸",
        "🏣",
        "💉",
        "🐋",
        "🎇",
        "🪕",
        "🐪",
        "🐚",
        "♉",
        "\U0001fa97",
        "🦶",
        "\U0001f6d6",
        "🦽",
        "🍲",
        "\U000e0060",
        "💋",
        "🧦",
        "🏅",
        "💦",
        "\U000e0035",
        "📕",
        "\U0001fab3",
        "🧲",
        "💰",
        "💬",
        "💚",
        "🧃",
        "🏊",
        "🧴",
        "🌵",
        "🚱",
        "🚸",
        "🚙",
        "🎶",
        "👪",
        "\U000e0068",
        "🍩",
        "😾",
        "💇",
        "🔳",
        "😗",
        "♌",
        "📷",
        "🆒",
        "🥼",
        "🌕",
        "🏆",
        "🙋",
        "\U000e0074",
        "🇶",
        "🟣",
        "🚡",
        "\U0001fad5",
        "🌐",
        "🚀",
        "📗",
        "💌",
        "⛲",
        "🍏",
        "🧇",
        "\U0001faa5",
        "🛄",
        "🌘",
        "🌀",
        "🪒",
        "🥺",
        "🧡",
        "🔡",
        "🏮",
        "🐹",
        "⚪",
        "🦚",
        "🤢",
        "🥨",
        "🗻",
        "📳",
        "🙈",
        "🇧",
        "🥂",
        "🛃",
        "🥱",
        "🍢",
        "🦪",
        "🌛",
        "🎮",
        "🔫",
        "🤔",
        "🏸",
        "🇯",
        "\U0001fac2",
        "\U000e004d",
        "🌖",
        "🐈",
        "🍙",
        "🐒",
        "🏬",
        "💐",
        "🇦",
        "🍄",
        "🤝",
        "🏹",
        "🏽",
        "💕",
        "🥎",
        "🍎",
        "\U000e0048",
        "🏓",
        "🔺",
        "🐁",
        "🐇",
        "\U0001fa9d",
        "\U0001f9ad",
        "🕌",
        "\U000e0046",
        "🛬",
        "📺",
        "🦜",
        "🚷",
        "\U000e0028",
        "🍣",
        "🦊",
        "🙆",
        "😦",
        "💾",
        "🥇",
        "📿",
        "🆖",
        "🥿",
        "🕘",
        "🎀",
        "🩲",
        "🥰",
        "\U0001fac1",
        "💍",
        "🌎",
        "🏥",
        "🚶",
        "🐬",
        "🚏",
        "🕓",
        "🍹",
        "🍉",
        "📙",
        "🤵",
        "🥖",
        "\U000e004b",
        "🤹",
        "⛎",
        "🔛",
        "😰",
        "🌺",
        "😈",
        "👻",
        "🔖",
        "🥣",
        "🔜",
        "🐅",
        "\U0001fa85",
        "⛄",
        "😒",
        "🦿",
        "😂",
        "🟡",
        "🧩",
        "🚴",
        "🥵",
        "🤒",
        "🩺",
        "📟",
        "🤧",
        "\U000e0029",
        "🇸",
        "🏄",
        "🙄",
        "🚫",
        "\U000e007e",
        "😝",
        "🌽",
        "🟠",
        "🚛",
        "🤬",
        "♿",
        "💩",
        "💏",
        "\U000e002f",
        "\U0001fa96",
        "💧",
        "🇨",
        "🔐",
        "🧟",
        "🐢",
        "\U0001f6fb",
        "🕺",
        "🔑",
        "😤",
        "👟",
        "🍐",
        "💞",
        "📢",
        "\U000e0069",
        "📏",
        "✨",
        "🚼",
        "\U000e007b",
        "🐫",
        "👆",
        "\U000e0045",
        "\U0001fa9f",
        "🖕",
        "⛳",
        "🐭",
        "🃏",
        "🧛",
        "🍤",
        "🧕",
        "🆙",
        "⚡",
        "🧺",
        "💄",
        "🥦",
        "🦦",
        "🇺",
        "🥻",
        "\U000e0063",
        "\U0001f9a3",
        "💎",
        "\U0001fac0",
        "🥝",
        "👜",
        "🚩",
        "👖",
        "🧂",
        "🟧",
        "\U000e007c",
        "📇",
        "🇰",
        "🚞",
        "🎬",
        "🪔",
        "\U0001faa4",
        "➗",
        "🥙",
        "🎐",
        "🚽",
        "🌾",
        "❗",
        "🕗",
        "🔽",
        "🟪",
        "\U0001fad2",
        "🥧",
        "🥳",
        "🟥",
        "🦞",
        "📼",
        "🏐",
        "\U0001fa9e",
        "🔃",
        "🥒",
        "🎵",
        "🕕",
        "🦳",
        "🍗",
        "👏",
        "🧜",
        "🐵",
        "🦙",
        "\U000e0051",
        "🐻",
        "🧈",
        "👙",
        "✅",
        "🤘",
        "🏪",
        "🥠",
        "\U000e0020",
        "\U000e0062",
        "🏑",
        "\U000e0079",
        "📬",
        "\U0001f9ab",
        "\U000e006e",
        "🚥",
        "📨",
        "🔮",
        "👤",
        "🍭",
        "📴",
        "🐍",
        "🇼",
        "🐉",
        "🚕",
        "🍑",
        "🎡",
        "🕛",
        "🚠",
        "🏫",
        "😐",
        "🚂",
        "🛫",
        "😿",
        "🍍",
        "💒",
        "💁",
        "🚦",
        "\U000e0061",
        "🚤",
        "😙",
        "⏪",
        "🦇",
        "⏩",
        "🌙",
        "🇲",
        "🍓",
        "🆚",
        "🧱",
        "👋",
        "\U000e0038",
        "🎤",
        "🕤",
        "🤸",
        "😌",
        "🕥",
        "🌳",
        "🎥",
        "🔊",
        "👩",
        "🤷",
        "⛽",
        "🦄",
        "🙁",
        "🟢",
        "🇫",
        "👎",
        "🤏",
        "🌜",
        "⛪",
        "\U000e0067",
        "🍼",
        "👰",
        "🥽",
        "🏼",
        "🔲",
        "🇳",
        "😶",
        "🥫",
        "🧧",
        "😊",
        "👹",
        "🌃",
        "👦",
        "🪂",
        "💵",
        "👿",
        "📡",
        "🐀",
        "📯",
        "🏴",
        "⏫",
        "🧬",
        "🌿",
        "🈶",
        "🪁",
        "⏰",
        "🔙",
        "🕋",
        "🈚",
        "🇱",
        "🧰",
        "🔸",
        "🙏",
        "🍚",
        "🚁",
        "🍘",
        "🔟",
        "😑",
        "🧢",
        "👄",
        "🎧",
        "🧞",
        "🩳",
        "😢",
        "\U000e0032",
        "\U000e005b",
        "🔹",
        "🍥",
        "👱",
        "😍",
        "📓",
        "🦁",
        "🐟",
        "\U000e0041",
        "♈",
        "🈹",
        "📀",
        "🔍",
        "🐼",
        "♊",
        "🧯",
        "👺",
        "🐑",
        "🕢",
        "👅",
        "⛅",
        "🤐",
        "😲",
        "🚬",
        "❓",
        "🌑",
        "🦘",
        "🇷",
        "\U0001fab4",
        "🥑",
        "🦰",
        "🇮",
        "♍",
        "🚇",
        "\U000e003d",
        "😟",
        "🌅",
        "🎱",
        "🔨",
        "🦒",
        "🔞",
        "🚭",
        "🏉",
        "\U0001f6d7",
        "🐕",
        "👶",
        "😨",
        "♎",
        "🥕",
        "\U000e005a",
        "🦏",
        "❔",
        "📈",
        "\U000e0058",
        "🧶",
        "🥘",
        "🙌",
        "💼",
        "🍠",
        "\U000e005d",
        "🟤",
        "🚨",
        "🤾",
        "🔆",
        "🤴",
        "🍅",
        "📪",
        "🧣",
        "👇",
        "👴",
        "📊",
        "\U000e003e",
        "🦌",
        "\U000e0078",
        "🍶",
        "😷",
        "😽",
        "🐦",
        "\U0001fad0",
        "💪",
        "🥓",
        "\U0001fa84",
        "👼",
        "🏀",
        "💊",
        "⛔",
        "\U000e004e",
        "⚫",
        "😋",
        "👉",
        "🍃",
        "🍾",
        "🤩",
        "🆗",
        "\U0001f9cb",
        "🔘",
        "🤰",
        "😀",
        "🚗",
        "🚾",
        "🤭",
        "🦅",
        "🦃",
        "🆎",
        "👭",
        "🛌",
        "🌱",
        "🙎",
        "🙇",
        "😹",
        "🧨",
        "🌗",
        "🩱",
        "🦀",
        "🧐",
        "😓",
        "🐂",
        "🚟",
        "✊",
        "\U000e0044",
        "🥴",
        "🚣",
        "\U000e0039",
        "♏",
        "🧳",
        "🧒",
        "🥭",
        "🦓",
        "🚢",
        "🤯",
        "👠",
        "✋",
        "😸",
        "\U0001faa3",
        "💮",
        "📶",
        "💭",
        "🚳",
        "👨",
        "♋",
        "🍧",
        "🍺",
        "🔈",
        "💗",
        "🎽",
        "🛺",
        "🧖",
        "🤨",
        "\U000e003c",
        "🩹",
        "🤳",
        "🚻",
        "🇬",
        "🐖",
        "🎯",
        "🍆",
        "🏰",
        "🈸",
        "🥔",
        "🍿",
        "💟",
        "🔰",
        "🔇",
        "🌔",
        "🥛",
        "🍬",
        "🤼",
        "🧻",
        "🥩",
        "👸",
        "🎨",
        "🔥",
        "🧹",
        "🍖",
        "😮",
        "🆔",
        "😱",
        "🔁",
        "😎",
        "😬",
        "🤶",
        "💷",
        "🥪",
        "🛶",
        "📝",
        "🛴",
        "🧭",
        "🎭",
        "🈳",
        "🏒",
        "🍪",
        "🦔",
        "🛒",
        "➰",
        "\U0001f90c",
        "🚘",
        "🌮",
        "🦂",
        "🔱",
        "🤓",
        "🈁",
        "🎸",
        "🦛",
        "\U000e002d",
        "🥞",
        "🛵",
        "\U0001faa0",
        "🏁",
        "\U000e006d",
        "🇵",
        "🔎",
        "📦",
        "🖤",
        "🎆",
        "🧷",
        "\U000e006c",
        "📞",
        "📭",
        "🎫",
        "⏳",
        "🛐",
        "🐷",
        "\U000e0022",
        "\U000e0024",
        "💖",
        "⚾",
        "🎋",
        "\U0001fab5",
        "📒",
        "👝",
        "🍮",
        "🐄",
        "⭕",
        "🍷",
        "📍",
        "👛",
        "🚐",
        "\U000e007d",
        "🌏",
        "🌚",
        "🪐",
        "🕑",
        "😏",
        "\U000e0075",
        "😅",
        "🎿",
        "🔉",
        "🥃",
        "🚵",
        "🟨",
        "🔵",
        "🐴",
        "🕦",
        "\U000e0073",
        "😻",
        "🙅",
        "◽",
        "➕",
        "🈲",
        "\U000e0065",
        "🕚",
        "🇹",
        "😠",
        "🥶",
        "🕖",
        "🔄",
        "🤪",
        "🤠",
        "👮",
        "🔋",
        "🤑",
        "\U000e007f",
        "🍌",
        "🤥",
        "💅",
        "⭐",
        "🤜",
        "🎃",
        "🚚",
        "💓",
        "🍜",
        "🚰",
        "🧀",
        "🐶",
        "🎰",
        "🤤",
        "🧥",
        "🍀",
        "\U000e0037",
        "🦥",
        "🏺",
        "🇽",
        "⬜",
        "🥚",
        "❎",
        "🦡",
        "🏇",
        "🦾",
        "🐤",
        "🐯",
        "👀",
        "👞",
        "🧆",
        "🏏",
        "🌒",
        "😘",
        "🚎",
        "🙀",
        "🤞",
        "\U0001f6fc",
        "🥗",
        "📂",
        "\U000e0040",
        "\U000e006f",
        "📄",
        "🎩",
        "🕡",
        "🚪",
        "🔧",
        "😩",
        "🗿",
        "🦗",
        "🌞",
        "\U0001f972",
        "🥀",
        "🎄",
        "🧪",
        "\U000e0043",
        "🔻",
        "🪑",
        "🔬",
        "\U000e0052",
        "📸",
        "🤽",
        "\U0001fa86",
        "🧙",
        "\U000e0025",
        "🙃",
        "🙂",
        "💘",
        "🌲",
        "🕣",
        "🕍",
        "\U0001faa7",
        "\U000e003a",
        "\U0001fad4",
        "♑",
        "🛅",
        "😭",
        "🔏",
        "❕",
        "🐆",
        "🏯",
        "📩",
        "🌸",
        "🔯",
        "🦋",
        "🦎",
        "🦱",
        "🔪",
        "🍯",
        "🐩",
        "😫",
        "🏿",
        "\U000e002b",
        "\U0001fa9c",
        "\U0001faa8",
        "📲",
        "🚺",
        "🍦",
        "🌹",
        "🦵",
        "🐽",
        "🌆",
        "🌴",
        "👣",
        "🧚",
        "🐊",
        "📋",
        "🆑",
        "🍫",
        "🧽",
        "💝",
        "🦸",
        "👽",
        "🗾",
        "🏧",
        "\U000e0026",
        "\U000e006b",
        "🤮",
        "🔂",
        "🌟",
        "🗼",
        "🐐",
        "🔩",
        "👥",
        "😃",
        "🩰",
        "🐎",
        "🐺",
        "🐓",
        "😵",
        "🚯",
        "➿",
        "💑",
        "🎣",
        "🦼",
        "🧠",
        "🔀",
        "🥮",
        "🐠",
        "🐗",
        "\U000e0054",
        "🦹",
        "💥",
        "🔷",
        "🐃",
        "🎢",
        "💺",
        "🛷",
        "🎴",
        "🎲",
        "🦻",
        "🇾",
        "🌝",
        "⌛",
        "🍂",
        "😼",
        "🦆",
        "\U0001fad3",
        "\U0001fad1",
        "💂",
        "\U0001fa99",
        "🔢",
        "🌄",
        "👓",
        "🥥",
        "⛵",
        "\U0001fa9b",
        "🍈",
        "🍔",
        "🛕",
        "👘",
        "👳",
        "🥯",
        "🥡",
        "🉐",
        "💙",
        "👕",
        "🪓",
        "🧏",
        "\U000e007a",
        "👐",
        "😣",
        "📫",
        "💨",
        "🧿",
        "\U0001fa83",
        "🐏",
        "\U0001fab6",
        "👲",
        "🧘",
        "🛁",
        "🌓",
        "🚖",
        "🐡",
        "🚆",
        "💡",
        "️",
        "🎌",
        "🧼",
        "👧",
        "\U0001f978",
        "📧",
        "🎂",
        "💛",
        "💫",
        "💔",
        "🐲",
        "🔌",
        "🇻",
        "🚊",
        "🟫",
        "🥐",
        "\U0001fab2",
        "🚔",
        "\U000e0055",
        "\U0001faa6",
        "🔣",
        "🎺",
        "🦠",
        "🏠",
        "🔴",
        "🐞",
        "😡",
        "🏢",
        "😕",
        "♒",
        "💳",
        "🚮",
        "🔚",
        "🤫",
        "🦕",
        "🌂",
        "🚓",
        "🧵",
        "🥬",
        "😔",
        "🥊",
        "🐛",
        "💽",
        "⏬",
        "🈺",
        "🦮",
        "🦉",
        "\U000e0047",
        "🎅",
        "\U000e0050",
        "🎦",
        "🤱",
    }


async def get_random_emoji_list(emoji_list: set) -> list:
    """Generates and returns a list of random emojis from a list of all available emojis.
    Uses secure random generator https://docs.python.org/3.6/library/secrets.html
    """
    return [emoji_list.pop() for x in range(secrets.randbelow(4) + 3)]


async def generate_key(filename):
    """Generates a key in form of a dictionary byte:emoji_list.
    Stores key as key.emojipher. Overwrites existing key if exists!

    1. Generate a list of all emojis.
    2. Generate a dictionary of bytes 0 - 256 and their list of emoji.
    3. Store key as key.emojipher.
    """

    print("👁👁 Generating key, I am not looking...")

    emojis = await get_all_emojis()

    key = {x: await get_random_emoji_list(emojis) for x in range(0, 256)}

    with open(filename + ".emojipher", "w") as f:
        # Write as string, can evaluate string to dict when reading key.
        f.write(str(key))

    print("🧑‍💻🤐 Key has been generated! Keep it safe.")


async def encrypt_data(filename: str, key: str):
    """Encrypts given file with given key. If such file exists, it is deleted!

    1. Load key.
    2. Iterate file bytes.
    2.1. Convert byte to int and find matching key in dict.
    2.2. Pick one random emoji from according list,
    2.3. Append to file.
    """

    print("🧙🏼🔥 Encrypting your data...")

    with open(key, "r") as fr:
        key = ast.literal_eval(fr.read())

    output_filename = filename + ".encrypted"

    # Remove existing file if needed.
    if os.path.exists(output_filename):
        os.remove(output_filename)

    with open(filename, "rb") as fr:
        byte = fr.read(1)
        while byte != b"":
            # Convert byte to int to match in key dictionary.
            b = int.from_bytes(byte, "little")
            byte = fr.read(1)

            with open(output_filename, "a") as fw:
                # Find matching random emoji and write to file.
                fw.write(secrets.choice(key[b]))

    print(
        "🕵 🕵️‍♂️ Your data has been encrypted and is safe from bioluminescent agents."
    )


async def decrypt_data(filename: str, key: str):
    """Given a filename and a key, decrypts data into original file."""

    print("👀👽 Decrypting data, make sure you are alone!")

    with open(key, "r") as fr:
        key = ast.literal_eval(fr.read())

    # Invert key, aka make each emoji in list of each key into a new key.
    # So one key with list of 5 emojis becomes 5 keys with same value of byte.
    inverted_key = {}
    for k, v in key.items():
        for e in v:
            inverted_key[e] = k.to_bytes(1, "little")

    output_filename = filename.replace(".encrypted", ".decrypted")

    if os.path.exists(output_filename):
        os.remove(output_filename)

    with open(filename, "r", encoding="utf-8") as fr:
        while True:
            c = fr.read(1)
            if not c:
                break

            with open(output_filename, "ab") as fw:
                fw.write(inverted_key[c])

    print("👨🏻‍💻🖨 Your data has been decrypted. Have fun!")


if __name__ == "__main__":
    parser = ArgumentParser(
        description=description, formatter_class=RawDescriptionHelpFormatter
    )
    generate = parser.add_argument_group("key generation")
    generate.add_argument("-g", "--generate", type=str, help="key name")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-e", "--encrypt", type=str, help="file(s) to encrypt")
    group.add_argument("-d", "--decrypt", type=str, help="file(s) to decrypt")
    group.add_argument("-c", "--changelog", action="store_true", help="see whats new!")
    parser.add_argument("-k", "--key", type=str, help="path to key")
    args = parser.parse_args()

    if args.generate:
        # await generate_key(args.generate)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(generate_key(args.generate))
        loop.close()

    elif args.encrypt:
        # await encrypt_data(args.encrypt, args.key)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(encrypt_data(args.encrypt, args.key))
        loop.close()

    elif args.decrypt:
        # await decrypt_data(args.decrypt, args.key)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(decrypt_data(args.decrypt, args.key))
        loop.close()
    elif args.changelog:
        print(changelog)
